apiVersion: v2
appVersion: 1.5.0
name: ociregistry
description: A pull-only, pull-through caching OCI image distribution server.
home: https://github.com/aceeric/ociregistry
type: application
keywords:
- oci
- distribution
- registry
- containerd
- mirror
- pull-through
- docker
sources:
- https://github.com/aceeric/ociregistry
version: 1.5.0
maintainers:
- name: Eric Ace
  url: https://github.com/aceeric
